runsim: storeStub.cpp
	g++ -std=c++11 -o runsim storeStub.cpp Simulation.h Simulation.cpp Store.h Store.cpp Customer.h Customer.cpp RentPattern.h RentPattern.cpp Rental.h Tool.h

clean:
	rm *.gch runsim
